// Loads the pitch dataset generated by scripts/build-data.mjs. The app reads
// the compact index (data/index.json, written at build time) and falls back
// to the full file in development. Per-pitch detail loads on demand.

let cache = null
const details = new Map()

export async function loadPitchData() {
  if (cache) return cache
  const base = import.meta.env.BASE_URL
  let res = await fetch(`${base}data/index.json`)
  if (res.status === 404) res = await fetch(`${base}data/pitches.json`)
  if (!res.ok) throw new Error(`Failed to load pitch data (HTTP ${res.status})`)
  cache = await res.json()
  return cache
}

/** Full record for one pitch, or null when the detail file is not available. */
export async function loadPitchDetail(id) {
  if (!/^[a-z0-9-]{1,40}$/i.test(id)) return null
  if (details.has(id)) return details.get(id)
  const p = fetch(`${import.meta.env.BASE_URL}data/p/${id}.json`)
    .then((res) => (res.ok ? res.json() : null))
    .catch(() => null)
  details.set(id, p)
  return p
}

/**
 * Cost model. Prices are known for curated bookable venues; park pitches and
 * cages default to free unless OSM says there's a fee; everything else is
 * honestly "unknown" rather than invented.
 * @returns {{ known: boolean, perHour: number|null }}
 */
export function costOf(pitch) {
  if (pitch.pricePerHour != null) {
    // The cheapest bookable slot: what a group pays for one game. An hour
    // unless the venue sells shorter slots (Powerleague's weekday 40 minutes).
    const slot =
      pitch.priceSlot && pitch.priceSlot.amount != null && pitch.priceSlot.minutes > 0
        ? { amount: pitch.priceSlot.amount, minutes: pitch.priceSlot.minutes }
        : { amount: pitch.pricePerHour, minutes: 60 }
    return { known: true, perHour: pitch.pricePerHour, slot }
  }
  if ((pitch.type === 'park' || pitch.type === 'cage') && pitch.fee !== true) {
    return { known: true, perHour: 0, slot: { amount: 0, minutes: 60 } }
  }
  return { known: false, perHour: null, slot: null }
}

export function isBounded(pitch) {
  return pitch.bounded === true || pitch.type === 'commercial' || pitch.type === 'cage'
}
