// Loads the pitch dataset generated by scripts/build-data.mjs (served from
// /data/pitches.json). The dataset is refreshed by CI from OpenStreetMap.

let cache = null

export async function loadPitchData() {
  if (cache) return cache
  const res = await fetch(`${import.meta.env.BASE_URL}data/pitches.json`)
  if (!res.ok) throw new Error(`Failed to load pitch data (HTTP ${res.status})`)
  cache = await res.json()
  return cache
}

/**
 * Cost model. Prices are known for curated bookable venues; park pitches and
 * cages default to free unless OSM says there's a fee; everything else is
 * honestly "unknown" rather than invented.
 * @returns {{ known: boolean, perHour: number|null }}
 */
export function costOf(pitch) {
  if (pitch.pricePerHour != null) return { known: true, perHour: pitch.pricePerHour }
  if ((pitch.type === 'park' || pitch.type === 'cage') && pitch.fee !== true) {
    return { known: true, perHour: 0 }
  }
  return { known: false, perHour: null }
}

export function isBounded(pitch) {
  return pitch.bounded === true || pitch.type === 'commercial' || pitch.type === 'cage'
}
